# Generated by Django 4.2.5 on 2023-09-22 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_task_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-date']},
        ),
    ]
