# Generated by Django 4.2.5 on 2023-09-22 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_alter_task_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-updated']},
        ),
        migrations.RenameField(
            model_name='task',
            old_name='date',
            new_name='created',
        ),
        migrations.AddField(
            model_name='task',
            name='updated',
            field=models.DateField(auto_now_add=True, default=''),
            preserve_default=False,
        ),
    ]
